### ISSUE TITLE
per-world-player.bypass dont work

### ISSUE THREAD

**Issue by MrBlasyMSK** [BlockHorizons/PerWorldPlayer#35]
https://streamable.com/jup0qr
Version dev 38
PHP 8.0.17
Pocketmine 4.2.6

My GroupsAPI config
```yml
  Creador:
    priority: 0
    permissions:
      - pocketmine.group.operator
      - per-world-player.bypass
      ```
