### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ddldsd** [BlockHorizons/PerWorldPlayer#8]
is there a way to exclude any worlds? I'm having some problems with some plugins that give automatically a kit

**Comment by Muqsit** [comment]
Excluding worlds doesn't make sense, like which inventory would an excluded world contain?

**Comment by Muqsit** [comment]
However, you can put all your excluded worlds in a bundle so all those worlds share the same inventory.
```yaml
Bundled-Worlds:
  BundleOfExcludedWorlds: # give a name to the bundle
    - kit_world_1 # names of excluded worlds
    - kit_world_2
    - kit_world_3

# kit_world_1, kit_world_2 and kit_world3 share the same inventory
```
